name: CI Advanced Training ML

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  train-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Check Python Environment
      run: |
        python --version
        pip --version

    - name: Install Python Dependencies
      run: |
        pip install mlflow pandas scikit-learn

    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run . -P data_path=employee_data_preprocessing/employee_data_preprocessing.csv -P C=1.0

    - name: Get Latest MLflow run_id
      run: |
        echo "Last Run ID:"
        ls -ltR mlruns || true

    - name: Archive MLflow Artifacts
      run: |
        mkdir -p upload_model
        cp -r MLProject/mlruns upload_model/
        tar -czf model_artifacts.tar.gz upload_model
      continue-on-error: true

    - name: Upload model artifacts to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: model-artifacts
        path: model_artifacts.tar.gz

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/attrition-model:latest MLProject

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker Image
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/attrition-model:latest ${{ secrets.DOCKER_USERNAME }}/attrition-model:v1

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/attrition-model:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/attrition-model:v1
